#cloud-config

# Cloudwatch configuration
write_files:
  - content: |
      {
        "agent": {
          "metrics_collection_interval": 30,
          "run_as_user": "root"
        },
        "logs": {
          "logs_collected": {
            "files": {
              "collect_list": [
                {
                  "file_path": "/var/log/messages",
                  "log_group_name": "messages",
                  "log_stream_name": "{instance_id}"
                },
                {
                  "file_path": "/var/log/secure",
                  "log_group_name": "secure",
                  "log_stream_name": "{instance_id}"
                },
                {
                  "file_path": "/var/log/dmesg",
                  "log_group_name": "dmesg",
                  "log_stream_name": "{instance_id}"
                },
                {
                  "file_path": "/var/log/ecs/ecs-agent.log",
                  "log_group_name": "ecs-agent.log",
                  "log_stream_name": "{instance_id}"
                },
                {
                  "file_path": "/var/log/cloud-init.log",
                  "log_group_name": "cloud-init.log",
                  "log_stream_name": "{instance_id}"
                },
                {
                  "file_path": "/var/log/cloud-init-output.log",
                  "log_group_name": "cloud-init-output.log",
                  "log_stream_name": "{instance_id}"
                }
              ]
            }
          }
        },
        "metrics": {
          "append_dimensions": {
            "AutoScalingGroupName": "$${aws:AutoScalingGroupName}",
            "ImageId": "$${aws:ImageId}",
            "InstanceId": "$${aws:InstanceId}",
            "InstanceType": "$${aws:InstanceType}"
          },
          "metrics_collected": {
            "cpu": {
              "measurement": [
                "cpu_usage_idle",
                "cpu_usage_iowait",
                "cpu_usage_user",
                "cpu_usage_system"
              ],
              "metrics_collection_interval": 30,
              "resources": [
                "*"
              ],
              "totalcpu": false
            },
            "disk": {
              "measurement": [
                "used_percent",
                "inodes_free"
              ],
              "metrics_collection_interval": 30,
              "resources": [
                "*"
              ]
            },
            "diskio": {
              "measurement": [
                "io_time"
              ],
              "metrics_collection_interval": 30,
              "resources": [
                "*"
              ]
            },
            "mem": {
              "measurement": [
                "mem_used_percent"
              ],
              "metrics_collection_interval": 30
            },
            "swap": {
              "measurement": [
                "swap_used_percent"
              ],
              "metrics_collection_interval": 30
            }
          }
        }
      }
    path: /etc/cloudwatch-agent.conf
    owner: root:root
    permissions: '0644'

runcmd:
  - yum install -y aws-cli wget amazon-cloudwatch-agent
  - echo ECS_CLUSTER="${cluster_name}" >> /etc/ecs/ecs.config
  - "echo 'ECS_AVAILABLE_LOGGING_DRIVERS=[\"json-file\",\"awslogs\"]' >> /etc/ecs/ecs.config"
  - /usr/bin/amazon-cloudwatch-agent-ctl -a stop
  - /usr/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/etc/cloudwatch-agent.conf -s
  - systemctl enable amazon-cloudwatch-agent.service
  - systemctl start amazon-cloudwatch-agent.service
